name: Publish to PyPI

on:
  push:
    tags:
      - "*"

jobs:
  pypi:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
      - name: Install dependencies
        run: pdm install
      - name: Build package
        run: pdm build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1